{% set data = load_setup_py_data() %}

package:
  name: rapidgzip
  version: {{ data.get('version') }}

# 'git_url' has the problem that I cannot specify a subfolder for the setup.py.
# 'path' fails to work because the relative symlinks in python/rapidgzip are copied as is rendering them unusable.
# The created sdist tar correctly dereferences all symbolic links and therefore works but we need to rename the
# <package>-<major>-<minor>-<patch>.tar.gz to src.tar in order to avoid having to edit this file on each version change.
source:
  url: src.tar

build:
  entry_points:
    - rapidgzip=rapidgzip:cli
  script_env:
    - RAPIDGZIP_BUILD_CXXOPTS=system
    - RAPIDGZIP_BUILD_ISAL=enable
    - RAPIDGZIP_BUILD_RPMALLOC=enable
    - RAPIDGZIP_BUILD_ZLIB=enable
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - nasm
    - cxxopts>=3,<4
  host:
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - python
    - setuptools >=46.4.0
    - wheel
    - cython >=0.29.24
    - pip
    - cxxopts>=3,<4
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
    - python

test:
  imports:
    - rapidgzip
  commands:
    - pip check
    - rapidgzip --help
  requires:
    - pip

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: MIT
  license_file:
   - LICENSE-APACHE
   - LICENSE-MIT
  summary: {{ data.get('description') }}

extra:
  recipe-maintainers:
    - mxmlnkn
